services:
  - type: web
    name: rsybattle-whatsapp-otp
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
